rails_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :translators

  resources :songs do
    resources :translations do
      member do
        put :check_link
      end
    end
  end
  
  resources :languages
  
  resources :genres
  
  root 'songs#index'
  
  get 'about' => 'welcome#about'
  get 'stats' => 'welcome#stats'
  get 'usage' => 'welcome#usage'
  
  get 'translations' => 'translations#index', :as => :translations
  get 'inactive_translations' => 'translations#inactive', :as => :inactive_translations

end

rails_app/app/views/layouts/_footer.html.erb
<nav id="footer" class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TTD_footer_navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="TTD_footer_navbar">
			<ul class="nav navbar-nav">
				<%= paginate @songs, theme: 'twitter-bootstrap-3', :pagination_class => 'pagination-sm' if ( current_page?(songs_path) || current_page?(root_path)) %>
				<%= paginate @translations, theme: 'twitter-bootstrap-3', :pagination_class => 'pagination-sm' if current_page?(translations_path) %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
			<div class="btn-group">
				<button type="button" class="btn btn-default myiconic"><%= link_to raw('<i class="fa fa-wordpress" style="color:#fb8f3d;"></i>' ), "http://www.eltangoteespera.com/p/dj-sasha-el-tordo-cv.html", target: '_blank' %></button>
				<button type="button" class="btn btn-default myiconic"><%= link_to raw('<i class="fa fa-github-alt" style="color:#000000;"></i>' ), "https://github.com/alexvicegrab/tangoLyricsDB", target: '_blank' %></button>
				<button type="button" class="btn btn-default myiconic"><%= link_to raw('<i class="fa fa-facebook-square" style="color:#3b5998;"></i>' ), "https://www.facebook.com/groups/410698905667019/", target: '_blank' %></button>
				<button type="button" class="btn btn-default myiconic"><%= link_to raw('<i class="fa fa-envelope" style="color:#dd4b39;"></i>' ), "mailto:tangotranslation@gmail.com" %></button>
				</div>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rails_app/app/views/layouts/_header.html.erb
<nav id="header" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TTD_main_navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to image_tag('favicon.png', height: 48, width: 48), root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="TTD_main_navbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?('songs') %>"><%= link_to "Songs", songs_path %></li>
        <li class="<%= 'active' if controller?('translators') %>"><%= link_to "Translators", translators_path %></li>
				<li class="<%= 'active' if controller?('languages') %>"><%= link_to "Languages", languages_path %></li>
				<li class="<%= 'active' if controller?('genres') %>"><%= link_to "Genres", genres_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Info<span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
						<li class="<%= 'active' if current_page?(usage_path) %>"><%= link_to "Usage", usage_path %></li>
						<li class="<%= 'active' if current_page?(stats_path) %>"><%= link_to "Stats", stats_path %></li>
						<li class="<%= 'active' if current_page?(inactive_translations_path) %>"><%= link_to "Admin", inactive_translations_path %></li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
				    <p class="navbar-text">User: <%= current_user.email %></p> <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "devise" %></li>
				  <% else %>
						<li><%= link_to "Sign In", new_user_session_path, class: "devise" %></li>
				  <% end %>
				</div>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rails_app/app/views/layouts/_search.html.erb
<a class="anchor" id="search_anchor"></a>

<%= form_tag songs_path, :method => 'get' do %>

<div class="form-group">
	<%= label_tag :title_has, "Title:", class: "sr-only" %>
	<%= text_field_tag :title_has, params[:title_has], class: "form-control", placeholder: "Title..." %>
</div>

<div class="form-group">
		<%= label_tag :genre_is, "Genre:", class: "sr-only" %>
		<%= select_tag :genre_is, options_from_collection_for_select(Genre.all, :id, :name, params[:genre_is]), class: "form-control", :prompt => "Genre..." %> 
</div>

<div class="form-group">
		<%= label_tag :composer_has, "Composer:", class: "sr-only" %>
		<%= text_field_tag :composer_has, params[:composer_has], class: "form-control", placeholder: "Composer..." %>
</div>

<div class="form-group">
	<%= label_tag :lyricist_has, "Lyricist:", class: "sr-only" %>
	<%= text_field_tag :lyricist_has, params[:lyricist_has], class: "form-control", placeholder: "Lyricist..." %>
</div>

<div class="form-group">
	<%= label_tag :year_min, "Years:", class: "sr-only" %>
	<div class="row">
		<div class="col-xs-6">
			<%= text_field_tag :year_min, params[:year_min], maxlength: 4, id: "TTD_year_search", class: "form-control", placeholder: "Min. year..." %>
		</div>
		<div class="col-xs-6">
			<%= text_field_tag :year_max, params[:year_max], maxlength: 4, id: "TTD_year_search", class: "form-control", placeholder: "Max. year..." %>
		</div>
	</div>
</div>

<div class="form-group">
	<%= label_tag :translation_num, "Translation #:", class: "sr-only" %>
	<%= text_field_tag :translation_num, params[:translation_num], class: "form-control", placeholder: "Num. of translations..." %>
</div>

<div class="form-group">
	<%= label_tag :language_is, "Language:", class: "sr-only" %>
	<%= select_tag :language_is, options_from_collection_for_select(Language.all, :id, :name, params[:language_is]), class: "form-control", :prompt => "Language..." %> 
</div>

<div class="form-group">
	<%= label_tag :translator_is, "Translator:", class: "sr-only" %>
	<%= select_tag :translator_is, options_from_collection_for_select(Translator.all, :id, :site_name, params[:translator_is]), class: "form-control", :prompt => "Translator..." %> 
</div>

<div class="form-group">
	<div class="row">
		<div class="col-xs-4">
	<%= button_tag(type: 'submit', class: "btn btn-info") do %>
	  <i class="fa fa-search"></i> <%= t('.search', :default => t("helpers.links.search")) %>
	<% end %>
	</div>
	<div class="col-xs-2"></div>
	<div class="col-xs-4">
	<%= link_to '<i class="fa fa-trash"></i> '.html_safe + t('.clear', :default => t("helpers.links.clear")),
	songs_path, :class => 'btn btn-default'  %>
		</div>
	</div>
</div>
<div class="form-group">
		<%= link_to '<i class="fa fa-pencil"></i> '.html_safe + t('.new', :default => t("helpers.links.new")) + ' Song',
		new_song_path,
		:class => 'btn btn-warning' %>
</div>

<% end %>

rails_app/app/views/layouts/_stats.html.erb
<h4>
	<%= Song.count.nil? ? 0 : Song.count %> songs
</h4>
<h4>
	<%= Translation.count.nil? ? 0 : Translation.count %> translations
</h4>
<h4>
	last Song: <%= Song.unscoped.last.nil? ? "N/A" : link_to(Song.unscoped.last.title, Song.unscoped.last) %>
</h4>
<h4>
	last Translation: <%= (Translation.unscoped.last.nil? or Translation.unscoped.last.song.nil?) ? "N/A" : link_to(Translation.unscoped.last.song.title, Translation.unscoped.last.song) %>
</h4>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TTdb | <%= (yield(:title).empty? ? "Tango Translation Database" : yield(:title)) %></title>
	<meta name="Description" content="Tango Translation Database links Argentine Tango song translations from Spanish to many languages">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag %>
	
	<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<div class="row">
		      <div id="content" class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
						
						<div id="search_link" class="visible-xs-block">
						  <%= link_to "Scroll to Search",
						              "#search_anchor", class: 'btn btn-lg btn-info' %>
						</div>
						
						<%= render partial: 'shared/flash', locals: { f: flash } %>
						
						<div class="page-header">
							<% if controller?('songs', 'translations') %>
								<h4 style="float:right">
									<%= yield(:display_count) %>
								</h4>
							<% end %>
							<h1><%= yield(:title) %></h1>
						</div>
						
						<%= yield %>
						
						<p class="spacer">&nbsp</p>
					
					</div>
		      <div id="sidebar" class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
						<div id="search">
		        	<%= render 'layouts/search' %>
						</div>
						<div id="stats">
							<%= render 'layouts/stats' %>
						</div>
		      </div>
					<p class="spacer">&nbsp</p>
		    </div>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>