rails_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :translators

  resources :songs do
    resources :translations do
      member do
        put :check_link
      end
    end
  end
  
  resources :languages
  
  resources :genres
  
  root 'songs#index'
  
  get 'about' => 'welcome#about'
  get 'stats' => 'welcome#stats'
  get 'usage' => 'welcome#usage'
  
  get 'translations' => 'translations#index', :as => :translations
  get 'inactive_translations' => 'translations#inactive', :as => :inactive_translations

end

rails_app/app/models/song.rb
class Song < ActiveRecord::Base
  include Filterable
  
  belongs_to :genre, counter_cache: true
  has_many :translations, -> { includes([:language, :song]).order('languages.iso') }, dependent: :delete_all
  has_many :languages, through: :translations
  
  # Scopes
  default_scope { order('title') }
  
  scope :title_has, -> (title) { where("lower(search_title) like ?", "%#{I18n.transliterate(title.downcase)}%") }
  scope :composer_has, -> (composer) { where("lower(composer) like ?", "%#{I18n.transliterate(composer.downcase)}%") }
  scope :lyricist_has, -> (lyricist) { where("lower(lyricist) like ?", "%#{I18n.transliterate(lyricist.downcase)}%") }
  scope :genre_is, -> (genre_id) { where("genre_id = ?", genre_id) }
  scope :year_min, -> (year) { where("year >= ?", year) }
  scope :year_max, -> (year) { where("year <= ?", year) }
  scope :translation_num, -> (translations_count) { where("translations_count = ?", translations_count) }
  scope :language_is, -> (language_id) { joins(:translations).merge( Translation.where("language_id = ?", language_id) ) } 
  scope :translator_is, -> (translator_id) { joins(:translations).merge( Translation.where("translator_id = ?", translator_id) ) } 
  
  # Validations
  validates :title,
  presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 2 }
  
  validates :genre_id,
  presence: true,
  numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    
  validates :year,
  allow_nil: true,
  numericality: {only_integer: true, greater_than_or_equal_to: 1866, less_than_or_equal_to: 2014}
  
  validates :composer,
  presence: true,
  length: { minimum: 4 }
      
  validates :lyricist,
  presence: true,
  length: { minimum: 4 }
    
  # Callbacks
  before_validation :normalise_song, on: [ :create, :update ]
  
  def youtube_link
    "http://www.youtube.com/results?search_query=#{self.title.gsub(/\s/,'+')}+#{self.genre.name.gsub(/\s/,'+')}"
  end
  
  def self.save_all
    # Useful to check that all translations are valid
    Song.all.each { |song| song.save! }
  end
  
  protected
  def normalise_song
    # Remove accents, white space, lower, titleise
    unless self.title.blank?
      self.title = self.title.strip.downcase.titleize
      self.search_title = I18n.transliterate(self.title.downcase)
    end
  
    unless self.composer.blank?
      self.composer = I18n.transliterate(self.composer.strip.downcase.titleize)
      # Fix "D'a" to "D'A" in composer & lyricist
      self.composer = self.composer.gsub("D'a", "D'A")
    end
    
    unless self.lyricist.blank?
      self.lyricist = I18n.transliterate(self.lyricist.strip.downcase.titleize)
      self.lyricist = self.lyricist.gsub("D'a", "D'A")
    end
  end  
end

rails_app/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @songs = Song.includes(:genre, :translations).filter( params.slice(:title_has,
    :genre_is, 
    :composer_has, 
    :lyricist_has, 
    :year_min, 
    :year_max, 
    :translation_num, 
    :language_is,
    :translator_is ))
    # Do not repeat records
    @songs = @songs.distinct
    
    @resultsCount = @songs.count.nil? ? 0 : @songs.count
    
    @songs = @songs.page params[:page]
  end
  
  def new
    @song = Song.new
  end
  
  def create
    # Display the hash
    #render plain: params[:song].inspect
    
    @song = Song.new(song_params)
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_path, notice: 'Song was successfully destroyed' }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end
  
  def song_params
    params.require(:song).permit(:title, :genre_id, :year, :composer, :lyricist)
  end
  
end

rails_app/app/helpers/songs_helper.rb
module SongsHelper
end

rails_app/app/views/songs/_composer_search.html.erb
<% composers = song.composer.split(/ \/ /) %>

<% composers.each_with_index do |a, index| %>
	<%= link_to(a, songs_path(:params => { :composer_has => a })) %>
	<% unless index == composers.size - 1 %>
		<%= " / " %> 
	<% end %>
<% end %>

rails_app/app/views/songs/_form.html.erb
<%= form_for @song, :html => { class: 'form-horizontal' } do |f| %>
	
	<%= render partial: 'shared/error', locals: {f: @song} %>
		
	<div class="form-group">
		<%= f.label :title, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :title, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :genre, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: true}, {class: 'form-control'} %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :composer, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :composer, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :lyricist, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :lyricist, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :year, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :year, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<%= f.submit nil, class: 'btn btn-primary' %>
			<%= link_to '<i class="fa fa-trash"></i> '.html_safe + t('.cancel', :default => t("helpers.links.cancel")),
				songs_path, class: 'btn btn-default' %>
		</div>
	</div>
<% end %>

rails_app/app/views/songs/_lyricist_search.html.erb
<% lyricists = song.lyricist.split(/ \/ /) %>

<% lyricists.each_with_index do |a, index| %>
	<%= link_to(a, songs_path(:params => { :lyricist_has => a })) %>
	<% unless index == lyricists.size - 1 %>
		<%= " / " %> 
	<% end %>
<% end %>

rails_app/app/views/songs/_year_search.html.erb
<%= song.year.nil? ? "" : link_to(song.year, songs_path(:params => { :year_min => song.year, :year_max => song.year })) %>

rails_app/app/views/songs/_youtube_icon.html.erb
<%= link_to raw('<i class="fa fa-youtube-play"></i>'), song.youtube_link,  :class => 'btn btn-xs btn-circle youtube_icon', target: '_blank' %>

rails_app/app/views/songs/edit.html.erb
<%- model_class = Song -%>
<% title t('.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize) %>

<%= render :partial => 'form' %>

rails_app/app/views/songs/index.html.erb
<%- model_class = Song -%>
<% title model_class.model_name.human.pluralize.titleize %>
<% display_count model_class, @resultsCount %>

<table class="table table-striped">
  <thead>
    <tr>
			<th><%= 'YouTube' %></th>
			<th><%= model_class.human_attribute_name(:title) %></th>
			<th><%= model_class.human_attribute_name(:genre) %></th>
      <th class="hidden-xs hidden-sm"><%= model_class.human_attribute_name(:composer) %></th>
      <th class="hidden-xs hidden-sm"><%= model_class.human_attribute_name(:lyricist) %></th>
      <th class="hidden-xs"><%= model_class.human_attribute_name(:year) %></th>
			<th><%= "T#" %></th>
      <th class='action_column'><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
		    <td><%= render partial: 'youtube_icon', locals: { song: song } %></td>
        <td><%= link_to song.title, song_path(song) %></td>
				<td><%= song.genre.blank? ? "N/A" : link_to(song.genre.name, genre_path(song.genre.id)) %></td>
        <td class="hidden-xs hidden-sm"><%= render partial: 'composer_search', locals: { song: song } %></td>
        <td class="hidden-xs hidden-sm"><%= render partial: 'lyricist_search', locals: { song: song } %></td>
        <td class="hidden-xs"><%= render partial: 'year_search', locals: { song: song } %></td>
				<td><%= song.translations.length %></td>
        <td class='action_column'>
			    <%= link_to raw('<i class="fa fa-eye"></i>'),
			                song_path(song),  :class => 'btn btn-xs btn-default' %>
          <%= link_to raw('<i class="fa fa-edit"></i>'),
                      edit_song_path(song), :class => 'btn btn-xs btn-warning' %>
          <%= link_to raw('<i class="fa fa-trash"></i>'),
                      song_path(song),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rails_app/app/views/songs/new.html.erb
<%- model_class = Song -%>
<% title t('.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize) %>

<%= render :partial => 'form' %>

rails_app/app/views/songs/show.html.erb
<%- model_class = Song -%>
<% title @song.title %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @song.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @song.genre.blank? ? "..." : link_to(@song.genre.name, @song.genre) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:composer) %>:</strong></dt>
  <dd><%= render partial: 'composer_search', locals: { song: @song } %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lyricist) %>:</strong></dt>
  <dd><%= render partial: 'lyricist_search', locals: { song: @song } %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= render partial: 'year_search', locals: { song: @song } %></dd>
  <dt><strong><%= 'YouTube' %>:</strong></dt>
  <dd><%= render partial: 'youtube_icon', locals: { song: @song } %></dd>
</dl>

<div class="form-actions">
  <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + t('.back', :default => t("helpers.links.back")),
              songs_path, :class => 'btn btn-default'  %>
  <%= link_to '<i class="fa fa-edit"></i> '.html_safe + t('.edit', :default => t("helpers.links.edit")),
              edit_song_path(@song), :class => 'btn btn-warning' %>
  <%= link_to '<i class="fa fa-trash"></i> '.html_safe + t('.destroy', :default => t("helpers.links.destroy")),
              song_path(@song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<h2>Translations</h2>
<%= render "translations/translation_header" %>
<%= render @song.translations %>
<%= render "translations/translation_footer" %>
 
<h2>Add a translation:</h2>
<%= form_for [@song, @song.translations.build], :html => { :class => 'form-horizontal' } do |f| %>
	<%= render "translations/form", :f => f %>
<% end %>