rails_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :translators

  resources :songs do
    resources :translations do
      member do
        put :check_link
      end
    end
  end
  
  resources :languages
  
  resources :genres
  
  root 'songs#index'
  
  get 'about' => 'welcome#about'
  get 'stats' => 'welcome#stats'
  get 'usage' => 'welcome#usage'
  
  get 'translations' => 'translations#index', :as => :translations
  get 'inactive_translations' => 'translations#inactive', :as => :inactive_translations

end

rails_app/app/models/translation.rb
class Translation < ActiveRecord::Base
  include Filterable
  include UrlHelper
  
  belongs_to :song, counter_cache: true
  belongs_to :language, counter_cache: true
  belongs_to :translator, counter_cache: true
  
  # Scopes
  # Next line overrides scoping in song Model, hence commented out
  # default_scope { order('created_at') }
  
  scope :language_is, -> (language_id) { Translation.where("language_id = ?", language_id) } 
  scope :translator_is, -> (translator_id) { Translation.where("translator_id = ?", translator_id) } 
  
  # Validations
  validates :link,
  presence: true,
  length: { minimum: 15 },
  url: true, # Custom URL validator in app/validators
  uniqueness: { case_sensitive: false, :scope => [ :language_id, :song_id ], message: "+ language combination must be unique" } # Sometimes a page may contain several translations (in different languages)
  
  validates :language_id,
  presence: true,
  numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    
  # Callbacks
  before_validation :normalise_translation, on: [ :create, :update ]
  after_validation :define_translator, :check_link
  
  def self.save_all
    # Useful to check that all translations are valid
    Translation.all.each { |translation| translation.save! }
  end
  
  protected
  def check_link
    self.active = check_url(self.link) unless self.link.blank?
  end
  
  def normalise_translation
    # Remove white space, replace https with http, unescape "#" character
    unless self.link.blank?
      self.link = self.link.strip
      self.link = URI.encode(URI.decode(self.link))
      #self.link = self.link.gsub('https', 'http')
      self.link = self.link.gsub('%23', '#') # Hash incorrectly rendered
      self.link = self.link.gsub('%20', '') # %20 sign creeping into links (e.g. YouTube links split at "=" sign)
    end
  end
  
  def define_translator
    # Check which translator this translation belongs to
    @translators = Translator.all
    unless self.link.blank?
      @translators.each do |t|
        if self.link.include?(t.site_link)
          self.translator_id = t.id
        end
      end
    end
  end
end

rails_app/app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  include UrlHelper
  
  before_action :set_translation, only: [:show, :edit, :update, :destroy, :check_link]
  before_action :authenticate_user!, except: [:index, :show, :create, :check_link]
  
  def inactive
    @translations = Translation.includes([:translator, :language, :song]).where(active: [false, nil]).order(['active', 'songs.title'])
  end
  
  def index
    @translations = Translation.includes([:translator, :language, :song]).filter( params.slice(:language_is, :translator_is )).order('songs.title')
    
    @resultsCount = @translations.count.nil? ? 0 : @translations.count
    
    @translations = @translations.page params[:page]
  end
  
  def show
  end
  
  def create
    @song = Song.find(params[:song_id])
    @translation = @song.translations.new(translation_params)
    
		respond_to do |format|
      if @translation.save
        format.html { redirect_to @song, notice: 'Thank you for adding a new translation!' }
        format.json { render :show, status: :created, location: @translation }
      else
        flash[:error] = @translation.errors.full_messages.to_sentence
        format.html { redirect_to @song }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
  end
  
  def check_link
    # @translation.check_link performed inherently during save validation
    @translation.save 
    redirect_to(:back)
  end
  
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @song, notice: 'Translation was successfully updated' }
        format.json { render :show, status: :ok, location: @translation }
      else
        flash[:error] = @translation.errors.full_messages.to_sentence
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to @song, notice: 'Translation was successfully destroyed' }
      format.json { head :no_content }
    end
  end
 
  private
    def set_translation
      @song = Song.find(params[:song_id])
      @translation = @song.translations.find(params[:id])
    end
  
    def translation_params
      params.require(:translation).permit(:link, :language_id)
    end
end

rails_app/app/helpers/translations_helper.rb
module TranslationsHelper
end

rails_app/app/views/translations/_active_icon.html.erb
<%= link_to raw(translation.active ? '<i type="button" class="fa fa-check"></i>' : '<i type="button" class="fa fa-exclamation-circle"></i>'),
	check_link_song_translation_path(translation.song, translation),
	method: :put,
	:class => translation.active.nil? ? 'btn btn-xs btn-warning btn-circle' : translation.active ? 'btn btn-xs btn-success btn-circle' : 'btn btn-xs btn-danger btn-circle' %>

rails_app/app/views/translations/_form.html.erb
<div class="form-group">
  <%= f.label :link, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :link, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :language, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
		<%= f.collection_select :language_id, Language.all, :id, :name, {prompt: true}, {class: 'form-control'} %>
  </div>
</div>

<div class="form-group">
	<div class="col-sm-10 col-sm-offset-2">
		<%= f.submit nil, class: 'btn btn-primary' %>
  	<%= link_to '<i class="fa fa-trash"></i> '.html_safe + t('.cancel', :default => t("helpers.links.cancel")),
            :back, class: 'btn btn-default' unless controller?('songs') %>
	</div>
</div>

rails_app/app/views/translations/_translation.html.erb
<tr>
  <td><%= render partial: 'translations/active_icon', object: translation, as: 'translation' %></td>
	<td class='search_column'><%= link_to raw("<i class='fa fa-link'></i>"), translation.link, :class => 'btn btn-xs btn-primary', data_toggle: 'tooltip', 'data-placement' => 'right', title: URI.decode(translation.link), rel: :tooltip, :target => "_blank" %></td>
	
	<% if controller?('translations') %>
	<td><%= link_to translation.song.title, song_path(translation.song) %></td>
	<% end %>
	
	<td><%= translation.translator_id == 0 ? "[Not categorised]" : ( Translator.exists?(translation.translator_id) ? link_to(Translator.find(translation.translator_id).site_name, translator_path(translation.translator_id) ) : "[Error]" ) %></td>
	<td class='search_column'><%= Language.exists?(translation.language_id) ? link_to(translation.language.iso, language_path(translation.language_id) ) : "[Error]" %></td>
	
	<td class='action_column'>
    <%= link_to raw('<i class="fa fa-eye"></i>'),
                song_translation_path(translation.song, translation),  :class => 'btn btn-xs btn-default' %>
    <%= link_to raw('<i class="fa fa-edit"></i>'),
                edit_song_translation_path(translation.song, translation),  :class => 'btn btn-xs btn-warning' %>
		<%= link_to raw('<i class="fa fa-trash"></i>'),
												[translation.song, translation],
					              method: :delete,
					              data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
												:class => 'btn btn-xs btn-danger' %>
	</td>
</tr>

rails_app/app/views/translations/_translation_footer.html.erb
	</tbody>
</table>

rails_app/app/views/translations/_translation_header.html.erb
<%- model_class = Translation -%>
<table class="table table-striped">
  <thead>
    <tr>
			<th class='search_column'><%= model_class.human_attribute_name(:active?) %></th>
      <th class='search_column'><%= model_class.human_attribute_name(:link) %></th>
			<%= raw('<th>Song</th>') if controller?('translations') %>
			<th><%= model_class.human_attribute_name(:translator) %></th>
			<th><%= model_class.human_attribute_name(:lang) %></th>
      <th class='action_column'><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

rails_app/app/views/translations/edit.html.erb
<%- model_class = Translation -%>
<% title t('.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize) %>

<%= render partial: 'shared/error', locals: {f: @translation} %>

<%= form_for [@song, @translation], :html => { class: 'form-horizontal' } do |f| %>
	<%= render :partial => 'form', object: f, as: 'f' %>
<% end %>

rails_app/app/views/translations/inactive.html.erb
<%- model_class = Translation -%>
<% title "Translations with access difficulties" %>

<%= render "translations/translation_header" %>
<%= render @translations %>
<%= render "translations/translation_footer" %>

rails_app/app/views/translations/index.html.erb
<%- model_class = Translation -%>
<% title model_class.model_name.human.pluralize.titleize %>
<% display_count model_class, @resultsCount %>

<%= render "translations/translation_header" %>
<%= render @translations %>
<%= render "translations/translation_footer" %>

rails_app/app/views/translations/show.html.erb
<%- model_class = Translation -%>
<% title @translation.song.title %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:song) %>:</strong></dt>
  <dd><%= link_to @translation.song.title, @translation.song %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= link_to URI.decode_www_form_component(@translation.link), @translation.link, :target => "_blank" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @translation.language.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active?) %>:</strong></dt>
  <dd><%= render partial: 'translations/active_icon', object: @translation, as: 'translation' %></dd>
</dl>

<div class="form-actions">
  <%= link_to '<i class="fa fa-chevron-left"></i> '.html_safe + t('.back', :default => t("helpers.links.back")),
              song_path(@translation.song), :class => 'btn btn-default'  %>
  <%= link_to '<i class="fa fa-edit"></i> '.html_safe + t('.edit', :default => t("helpers.links.edit")),
              edit_song_translation_path(@translation.song, @translation), :class => 'btn btn-warning' %>
  <%= link_to '<i class="fa fa-trash"></i> '.html_safe + t('.destroy', :default => t("helpers.links.destroy")),
              [@translation.song, @translation],
              method: :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>